- name: disable password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no' 

- name: restart 
  service:
    name: ssh
    state: restarted